import type { ContainerFormat } from '@/domain/media/container';
import type { MediaProcessor, ProcessOptions } from '@/application/mediaProcessor';
import type { MediaRecord } from '../domain/mediaRecord';

/** A media file on local disk, valid only inside `MediaStorage.withLocalFile`. The path never leaves the server. */
export interface LocalMediaFile {
  readonly path: string;
}

export type StorageErrorKind = 'too-large' | 'not-found' | 'aborted' | 'failed';

export class StorageError extends Error {
  readonly kind: StorageErrorKind;
  constructor(kind: StorageErrorKind, message?: string) {
    super(message ?? kind);
    this.name = 'StorageError';
    this.kind = kind;
  }
}

/**
 * Temporary media storage. Application code must not know whether this is a
 * local disk, object storage or anything else. Ids are generated by the
 * server; user filenames never reach storage.
 */
export interface MediaStorage {
  /** Streams `source` into storage. Never buffers the whole file. Cleans up partial data on any failure. */
  save(id: string, source: AsyncIterable<Uint8Array>, options: { maxBytes: number; signal?: AbortSignal }): Promise<{ sizeBytes: number }>;
  exists(id: string): Promise<boolean>;
  read(id: string): AsyncIterable<Uint8Array>;
  /** Runs `fn` with a local file for tools that need one (object-store adapters would download to scratch space first). */
  withLocalFile<T>(id: string, fn: (file: LocalMediaFile) => Promise<T>): Promise<T>;
  /** Idempotent. */
  delete(id: string): Promise<void>;
  /** Removes stored files older than `olderThanMs` (orphans left by failed deletes or crashes). */
  cleanup(options: { olderThanMs: number }): Promise<{ removed: number }>;
  /** Removes everything this storage owns. Used at startup and shutdown, when no in-memory record can refer to a file. */
  purge(): Promise<{ removed: number }>;
}

export interface MediaRepository {
  get(id: string): MediaRecord | undefined;
  set(record: MediaRecord): void;
  delete(id: string): void;
  expired(now: number): MediaRecord[];
}

export type MediaInput = LocalMediaFile & { readonly container: ContainerFormat };

/** Server processor: the shared metadata port plus a decode smoke test. */
export interface ServerMediaProcessor extends MediaProcessor<MediaInput> {
  /** Confirms the start of the video stream actually decodes. Rejects with MediaIngestionError('invalid-media') if not. */
  verifyDecodable(input: MediaInput, options?: ProcessOptions): Promise<void>;
}

export interface Logger {
  debug(msg: string, fields?: Record<string, unknown>): void;
  info(msg: string, fields?: Record<string, unknown>): void;
  warn(msg: string, fields?: Record<string, unknown>): void;
  error(msg: string, fields?: Record<string, unknown>): void;
}
